### ISSUE TITLE
Criar hook para somar "Select page" no customizer da Featured Page section

### ISSUE THREAD

**Issue by diegorojas** [diegorojas/tema-coletivo#1]
Somar como na linha https://github.com/diegorojas/tema-coletivo/blob/master/inc/customizer.php#L34 um hook para pega-lo como conteúdo padrão na Sessão Featured Page e não dar erro. Quando você seleciona o tema e vai começar a mexer nessa seção, veja o erro:

![notice-featured-page](https://cloud.githubusercontent.com/assets/3632627/19609301/1c26e188-97b5-11e6-85be-de519ec84d07.png)

Notice: Trying to get property of non-object in /home/brasil/public_html/beta/wp-includes/post-template.php on line 298

**Comment by everaldomatias** [comment]
@diegorojas não consegui reproduzir o erro. Pode me ajudar.
E me diga se o que precisa é apenas fazer uma condição para verificar se existe conteúdo setado, é isso?

**Comment by diegorojas** [comment]
Ei mano, valeu. É isso sim. Uma condicional para um conteúdo default.. Mas é de um select, o select de pages.

Para ver o erro tente desativar e ativar de novo o tema.

**Comment by diegorojas** [comment]
Ei mano, valeu. É isso sim. Uma condicional para um conteúdo default.. Mas
é de um select, o select de pages.

Para ver o erro tente desativar e ativar de novo o tema.

**Comment by everaldomatias** [comment]
Mano, ja desativei e ativei o tema e nada. Tem alguma coisa ai no seu dev que está diferente e o problema não aparece pra mim.

Melhor seria conversarmos num hangout e vc compartilhar a tela comigo e vice versa.

**Comment by everaldomatias** [comment]
PS. fiz o que sugeriu no local e no beta e nada do erro aparecer.

**Comment by diegorojas** [comment]
Belez Eve! Valeu mano, tentamos fazer desse jeito ai compartilhando tela. Comigo o erro não aparece só local não, já aconteceu no beta.
